#! /bin/bash

if [ $UID -eq 0 ]; then
    if getent passwd theia > /dev/null; then
        if [ "$USER" != "" ]; then
            usermod -l "$USER" theia
	    sed -i "/app_account/s/theia/$USER/" /etc/matchhostfsowner/config.yml
	fi
    fi

    # Change file permissions to match host user.
    # That will, in turn, call this script again, except the UID will be 2000
    MHF_HOST_UID=2000 MHF_HOST_GID=2000 \
    exec /sbin/matchhostfsowner /theia/theia-entrypoint
elif [ $UID -eq 2000 ]; then
    cd /theia
    exec yarn theia start /home --hostname 0.0.0.0 --port 3000
else
    cd /home
    exec /bin/bash
fi
