name: theia-cs46 CI to Docker hub

on:
  push:
    branches: [ master ]
    paths: 
      - 'theia-cs46/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./theia-cs46/
          file: ./theia-cs46/Dockerfile
          push: true
          tags: zedchance/theia-cs46:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
